### ISSUE TITLE
List of issues

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/wv#1]
- [ ] Merge exts package, see #2 for more details
- [ ] Add spatial wavelet transforms and create wrappers, see #3 for more details
- [ ] Wavelet decompositions, see #4 for more details
- [ ] Wavelet variances, see #5 (requires more details from @robertomolinari and @HaotianXu)
